baseURL = "https://example.com"
languageCode = "en-us"
title = "md catchen"
#theme = "noteworthy"
enableRobotsTXT = true
paginate = 10 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""


[taxonomies]
  tag = "tags"

[author]
	name = "michael"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	description = "computational and quantitative ecology"
    showReadMore = false
	email = "#"
    twitter = "http://www.twitter.com/mdcatchen"
    github = "http://www.github.com/gottacatchenall"
    orcid = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "reseach"
	name = "research"
	url = "/research/"
	weight = 2

[[menu.main]]
	name = "publications"
	identifier = "publications"
	url = "/publications/"
	weight = 3
